### ISSUE TITLE
The упоминания "инородных" продуктов в описании

### ISSUE THREAD

**Issue by nluzgin** [Swordfish-Security/hub-tool-converters#18]
Лично не сталкивался, но глаз зацепился за хардкод дескрипшена:
https://github.com/Swordfish-Security/hub-tool-converters/blob/main/converters/parsers/semgrep.py#L106

Кажется, что упоминание "https://github.com/DefectDojo/django-DefectDojo/issues/8435" в описании хаба излишни.
Возможно такие рудименты также есть где-то ещё.

**Comment by serpol1** [comment]
Решили в https://github.com/Swordfish-Security/hub-tool-converters/pull/28
Спасибо!
