### ISSUE TITLE
Разный регистр при импорте и scancodebase у CLI и скриптов конвертации

### ISSUE THREAD

**Issue by nluzgin** [Swordfish-Security/hub-tool-converters#21]
Конвертор принимает исключительно Uppercase:

`Converter: error: argument -bt/--build-tool: invalid choice: 'npm' (choose from 'MAVEN', 'GRADLE', 'PIP', 'NUGET', 'NPM')`

CLI исключительно lowercase:
`2024-09-06 14:13:59.480 (scan_codebase) ERROR - Status code: 400. Reason: The build tool is not valid. Required one of maven, gradle, nuget, npm, pip, composer, go mod.`

**Comment by nluzgin** [comment]
@serpol https://github.com/Swordfish-Security/hub-tool-converters/pull/26 - это я тоже починил

**Comment by serpol1** [comment]
Спасибо!
