### ISSUE TITLE
Отсутствуют поддерживаемые хабом build-tool

### ISSUE THREAD

**Issue by nluzgin** [Swordfish-Security/hub-tool-converters#22]
Не поддерживаются:

- go mod
- сomposer

`Converter: error: argument -bt/--build-tool: invalid choice: 'сomposer' (choose from 'MAVEN', 'GRADLE', 'PIP', 'NUGET', 'NPM')`

**Comment by nluzgin** [comment]
Converter: error: argument -bt/--build-tool: invalid choice: 'GO MOD' (choose from 'MAVEN', 'GRADLE', 'PIP', 'NUGET', 'NPM')

**Comment by serpol1** [comment]
Исправлено в https://github.com/Swordfish-Security/hub-tool-converters/pull/26

**Comment by nluzgin** [comment]
Сам завёл - сам починил. Нраица))))))))))
